import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Professional={id:string;name:string;trade:string;category:string;city:string;rating:number;jobs:number;verified:boolean;priceFrom:number;bio:string};
const API=import.meta.env.VITE_API_URL||'http://localhost:4000';
const categories=[['electricidad','⚡','Electricidad'],['gasfiteria','🔧','Gasfitería'],['carpinteria','🪚','Carpintería'],['pintura','🖌️','Pintura'],['limpieza','🧹','Limpieza'],['construccion','🧱','Construcción'],['tecnologia','💻','Tecnología'],['jardineria','🌱','Jardinería']];

function App(){
 const [query,setQuery]=useState(''); const [category,setCategory]=useState(''); const [city,setCity]=useState(''); const [items,setItems]=useState<Professional[]>([]); const [loading,setLoading]=useState(false); const [selected,setSelected]=useState<Professional|null>(null); const [login,setLogin]=useState(false);
 const search=async()=>{setLoading(true);try{const u=new URL(`${API}/api/professionals`);if(query)u.searchParams.set('q',query);if(category)u.searchParams.set('category',category);if(city)u.searchParams.set('city',city);const r=await fetch(u);setItems(await r.json())}finally{setLoading(false)}};
 useEffect(()=>{search()},[]);
 const money=(n:number)=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
 const headline=useMemo(()=>query?`Profesionales para “${query}”`:'Profesionales destacados', [query]);
 return <div className="app">
  <header><a className="brand" href="#top">Oficio<span>Ya</span></a><nav><a href="#servicios">Servicios</a><a href="#como">Cómo funciona</a><a href="#profesionales">Profesionales</a></nav><button className="ghost" onClick={()=>setLogin(true)}>Ingresar</button></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><div className="pill">🇨🇱 Servicios locales de confianza</div><h1>Encuentra a la persona indicada para tu <span>oficio.</span></h1><p>Compara profesionales, revisa valoraciones, solicita cotizaciones y coordina todo en un solo lugar.</p><div className="searchbox"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="¿Qué necesitas? Ej. electricista"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="📍 Ciudad o comuna"/><button onClick={search}>{loading?'...':'Buscar'}</button></div></div><div className="hero-card"><div className="mini-map">📍</div><strong>Profesionales cerca de ti</strong><span>Verificados y con reputación</span><div className="avatars"><i>CG</i><i>MP</i><i>JS</i><b>+120</b></div></div></section>
   <section id="servicios" className="section"><div className="section-head"><div><small>ENCUENTRA LO QUE NECESITAS</small><h2>Explora por oficio</h2></div></div><div className="cat-grid">{categories.map(([id,icon,name])=><button className={category===id?'cat active':'cat'} key={id} onClick={()=>{setCategory(id);setTimeout(search,0)}}><b>{icon}</b><span>{name}</span></button>)}</div></section>
   <section id="profesionales" className="section results"><div className="section-head"><div><small>OPCIONES PARA TI</small><h2>{headline}</h2></div><span>{items.length} resultados</span></div>{loading?<div className="empty">Buscando profesionales…</div>:<div className="pro-grid">{items.map(p=><article className="pro" key={p.id}><div className="pro-top"><div className="avatar">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div>{p.verified&&<label>✓ Verificado</label>}</div><h3>{p.name}</h3><p className="trade">{p.trade} · {p.city}</p><p>{p.bio}</p><div className="rating">★ {p.rating} <span>({p.jobs} trabajos)</span></div><div className="pro-bottom"><strong>Desde {money(p.priceFrom)}</strong><button onClick={()=>setSelected(p)}>Ver perfil</button></div></article>)}</div>}</section>
   <section id="como" className="how"><div><small>ASÍ DE SIMPLE</small><h2>Contratar un oficio no debería ser complicado.</h2></div><div className="steps"><div><b>01</b><h3>Busca</h3><p>Encuentra profesionales por oficio y ubicación.</p></div><div><b>02</b><h3>Compara</h3><p>Revisa experiencia, reputación y cotizaciones.</p></div><div><b>03</b><h3>Coordina</h3><p>Habla directamente y agenda tu trabajo.</p></div></div></section>
   <section className="cta"><div><small>¿OFRECES UN SERVICIO?</small><h2>Haz crecer tu oficio con OficioYa.</h2><p>Crea tu perfil profesional y recibe nuevas solicitudes.</p></div><button onClick={()=>setLogin(true)}>Quiero ofrecer mis servicios →</button></section>
  </main><footer><strong>OficioYa</strong><span>Conectando personas con buenos profesionales.</span><span>© 2026</span></footer>
  {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="avatar big">{selected.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h2>{selected.name}</h2><p className="trade">{selected.trade} · {selected.city}</p><div className="rating">★ {selected.rating} · {selected.jobs} trabajos</div><p>{selected.bio}</p><button className="primary" onClick={()=>alert('Para solicitar este servicio, primero debes ingresar.')}>Solicitar servicio</button></div></div>}
  {login&&<div className="modal" onClick={()=>setLogin(false)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLogin(false)}>×</button><h2>Ingresar a OficioYa</h2><p>Accede para solicitar servicios, cotizar y conversar con profesionales.</p><input className="field" placeholder="Correo electrónico"/><input className="field" type="password" placeholder="Contraseña"/><button className="primary" onClick={()=>setLogin(false)}>Continuar</button><small>El registro y autenticación completa están disponibles en la API.</small></div></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
